import type { Strategy } from "../types.js";

export const BUILT_IN_STRATEGIES: Strategy[] = [
  {
    name: "first-principles",
    description: "Decompose assumptions and rebuild understanding from ground truth",
    whenToUse: "When tackling complex problems where conventional wisdom may be misleading",
    steps: [
      "Identify the core problem or question",
      "List all assumptions being made",
      "Challenge each assumption — is it actually true?",
      "Identify the fundamental truths that remain",
      "Rebuild your understanding from these truths",
      "Synthesize a solution based on first principles",
    ],
    guidingQuestions: [
      "What am I assuming that might not be true?",
      "What is the most basic truth I can establish here?",
      "If I started from scratch, would I arrive at the same conclusion?",
      "What would a beginner with no assumptions think?",
    ],
    reflectChecks: [
      "Have assumptions been identified and challenged?",
      "Are conclusions built on verified truths, not inherited beliefs?",
      "Is the reasoning independent of analogies or precedent?",
    ],
  },
  {
    name: "red-team",
    description: "Attack your own conclusions to find weaknesses and blind spots",
    whenToUse: "When validating important decisions or checking for blind spots",
    steps: [
      "State your current position or conclusion clearly",
      "Assume the position is wrong — find reasons why",
      "Identify the weakest assumptions in the argument",
      "Consider adversarial scenarios and edge cases",
      "Assess: does the position survive the attack?",
      "Strengthen or revise the position based on findings",
    ],
    guidingQuestions: [
      "If I had to argue against this, what would I say?",
      "What's the strongest counterargument?",
      "Under what conditions does this fail?",
      "Who would disagree with this and why?",
    ],
    reflectChecks: [
      "Has the position been attacked from multiple angles?",
      "Were counterarguments genuinely strong, not straw men?",
      "Have edge cases and failure modes been considered?",
    ],
  },
  {
    name: "convergent",
    description: "Narrow from many options to one decision through systematic evaluation",
    whenToUse: "When choosing between multiple viable alternatives",
    steps: [
      "List all available options (exhaustively)",
      "Define evaluation criteria with weights",
      "Eliminate options that fail must-have criteria",
      "Score remaining options against weighted criteria",
      "Identify the top 2-3 options",
      "Make a final decision with documented rationale",
    ],
    guidingQuestions: [
      "Have I considered all reasonable alternatives?",
      "Are my criteria reflecting actual priorities?",
      "Am I weighting criteria correctly?",
      "Would I defend this choice to a skeptic?",
    ],
    reflectChecks: [
      "Were at least 3 alternatives considered?",
      "Are criteria defined and weighted?",
      "Is there a clear winner with documented rationale?",
    ],
  },
  {
    name: "divergent",
    description: "Generate ideas freely without judgment — quantity over quality",
    whenToUse: "When brainstorming, exploring possibilities, or stuck on a problem",
    steps: [
      "State the seed idea or problem",
      "Generate as many ideas as possible (no filtering)",
      "Branch freely — wild ideas welcome",
      "Combine and remix ideas",
      "Group similar ideas into themes",
      "Select promising ideas for deeper exploration",
    ],
    guidingQuestions: [
      "What's the most unconventional approach?",
      "What would the opposite solution look like?",
      "Can I combine two existing ideas into something new?",
      "What constraint could I remove to enable new possibilities?",
    ],
    reflectChecks: [
      "Were at least 5 distinct ideas generated?",
      "Was judgment deferred during ideation?",
      "Were ideas combined or remixed?",
    ],
  },
  {
    name: "root-cause",
    description: "Systematic investigation to find the real cause, not just symptoms",
    whenToUse: "When debugging, investigating failures, or diagnosing problems",
    steps: [
      "Describe the observed symptoms precisely",
      "Ask 'why?' to dig deeper (5 whys technique)",
      "Map potential causes (fishbone/Ishikawa)",
      "Eliminate causes through evidence",
      "Isolate the root cause",
      "Verify by predicting: if this is the cause, what else should be true?",
    ],
    guidingQuestions: [
      "Am I solving the symptom or the root cause?",
      "What changed recently that could explain this?",
      "Can I reproduce this consistently?",
      "What evidence would disprove my current theory?",
    ],
    reflectChecks: [
      "Were at least 3 levels of 'why' explored?",
      "Was the root cause verified with evidence?",
      "Were alternative causes considered and eliminated?",
    ],
  },
  {
    name: "decision-matrix",
    description: "Structured comparison of alternatives using weighted criteria",
    whenToUse: "When making high-stakes decisions with multiple factors to balance",
    steps: [
      "Define the decision to be made",
      "List all viable options",
      "Define criteria (functional, non-functional, business, technical)",
      "Assign weights to criteria (must total 100%)",
      "Score each option against each criterion (1-5)",
      "Calculate weighted scores",
      "Document the recommendation with rationale",
    ],
    guidingQuestions: [
      "Are all stakeholder concerns represented in the criteria?",
      "Am I biased toward any option?",
      "What's the cost of being wrong?",
      "Is there a reversible option that scores well enough?",
    ],
    reflectChecks: [
      "Are criteria weighted and documented?",
      "Were scores justified, not arbitrary?",
      "Was the recommendation clearly stated with rationale?",
    ],
  },
];
